[package]
name = "brainfuck_plus-core"
version = "0.1.37"
edition = "2021"
authors = ["F1L1Pv2 <filipscave@gmail.com>"]
description = "core components of bfp language"
readme = "README.md"
repository = "https://github.com/F1L1Pv2/brainfuck_plus-core"
license = "MIT OR Apache-2.0"

[dependencies]
